title: "Akylas Stratigakos"
name: "Akylas Stratigakos"
email: "a.stratigakos@ucl.ac.uk"
description: "Short bio here."

url: "https://akylasstrat.github.io"
baseurl: ""   # must match the repo name with a leading slash

# collections:
#   talks:
#     output: true
#     permalink: /talks/:name/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-scholar


scholar:
  source: ./_bibliography
  bibliography: papers.bib
  style: apa                # change to ieee, acm, nature, etc. if you prefer
  # bibliography_template: bibliography  # uncomment if you later add a custom template

# defaults:
#   - scope: { path: "_posts" }
#     values:
#       layout: post
#       author: "Akylas Stratigakos"
#   - scope: { path: "_pages" }
#     values:
#       layout: page
#   - scope: { path: "_talks" }
#     values:
#       layout: talk
