title: "Akylas Stratigakos"
name: "Akylas Stratigakos"
email: "you@example.com"
description: "Short bio here."
url: "https://akylasstrat.github.io"     # no trailing slash
baseurl: "/akylas-stratigakos.github.io" # MUST start with a slash

markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  talks:
    output: true
    permalink: /talks/:name/

defaults:
  - scope: { path: "_posts" }
    values:
      layout: post
      author: "Akylas Stratigakos"
  - scope: { path: "_pages" }
    values:
      layout: page
  - scope: { path: "_talks" }
    values:
      layout: talk
