title: "Akylas Stratigakos"
name: "Akylas Stratigakos"
email: "you@example.com"
description: "Short bio here."

url: "https://akylasstrat.github.io"
baseurl: ""   # must match the repo name with a leading slash

markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar

collections:
  pages:
    output: true
    permalink: /:name/
    
scholar:
  source: ./_bibliography
  bibliography: papers.bib
  style: apa

collections:
  talks:
    output: true
    permalink: /talks/:name/

# defaults:
#   - scope: { path: "_posts" }
#     values:
#       layout: post
#       author: "Akylas Stratigakos"
#   - scope: { path: "_pages" }
#     values:
#       layout: page
#   - scope: { path: "_talks" }
#     values:
#       layout: talk
